initial complete version of setup_python_env

diff --git a/scripts/setup_python_venv b/scripts/setup_python_venv
--- a/scripts/setup_python_venv
+++ b/scripts/setup_python_venv
@@ -50,15 +50,27 @@ source $WORK_DIR/$VENV_NAME/bin/activate
 ###
 # Install required modules except moo
 ###
-curl -O ... requirements_moo.txt
-python -m pip install -r requirements.txt
+curl -O https://raw.githubusercontent.com/DUNE-DAQ/daq-buildtools/dingpf/python-venv/scripts/pyvenv_requirements.txt
+python -m pip install -r pyvenv_requirements.txt
+if [[ $? != "0" ]]; then
+    echo "ERROR [`eval $timenow`]: Installing required modules failed."
+    exit 12
+fi
 
-# check success.
-
- 
 ###
 # special handling of the moo module since PyPI has a module with same name.
 ###
-# check if moo exists..
-# install if not..
-pip install git+git://github.com/brettviren/moo.git
+if python -c "import moo" &> /dev/null; then
+    echo "INFO [`eval $timenow`]: moo is installed."
+    pip list|grep moo
+else
+    echo "INFO [`eval $timenow`]: moo is not installed. Install it now."
+    pip install git+git://github.com/brettviren/moo.git
+    if [[ $? != "0" ]]; then
+        echo "ERROR [`eval $timenow`]: Installing moo failed."
+        exit 13
+    fi
+fi
+
+
+echo "$VEVN_NAME has been activated, use \"deactivate\" to exit the venv."
