add moo into the requirements.txt with URL to its github repo; remove special handling of moo in the setup_python_env script

diff --git a/scripts/setup_python_venv b/scripts/setup_python_venv
--- a/scripts/setup_python_venv
+++ b/scripts/setup_python_venv
@@ -81,17 +81,17 @@ fi
 ###
 # special handling of the moo module since PyPI has a module with same name.
 ###
-if python -c "import moo" &> /dev/null; then
-    echo "INFO [`eval $timenow`]: moo is installed."
-    pip list|grep moo
-else
-    echo "INFO [`eval $timenow`]: moo is not installed. Install it now."
-    pip install git+git://github.com/brettviren/moo.git
-    if [[ $? != "0" ]]; then
-        echo "ERROR [`eval $timenow`]: Installing moo failed."
-        exit 13
-    fi
-fi
+#if python -c "import moo" &> /dev/null; then
+#    echo "INFO [`eval $timenow`]: moo is installed."
+#    pip list|grep moo
+#else
+#    echo "INFO [`eval $timenow`]: moo is not installed. Install it now."
+#    pip install git+git://github.com/brettviren/moo.git
+#    if [[ $? != "0" ]]; then
+#        echo "ERROR [`eval $timenow`]: Installing moo failed."
+#        exit 13
+#    fi
+#fi
 
 
 echo "INFO [`eval $timenow`]: $VEVN_NAME has been activated, use \"deactivate\" to exit the venv."
